module Shared.Database.Mapping.DocumentTemplate.DocumentTemplateDraftList where

import Database.PostgreSQL.Simple

import Shared.Model.DocumentTemplate.DocumentTemplateDraftList

instance FromRow DocumentTemplateDraftList
