module Shared.Database.Mapping.KnowledgeModel.Editor.KnowledgeModelEditorSuggestion where

import Database.PostgreSQL.Simple

import Shared.Model.KnowledgeModel.Editor.KnowledgeModelEditorSuggestion

instance FromRow KnowledgeModelEditorSuggestion
