module Shared.Service.KnowledgeModel.Editor.Collaboration.CollaborationAcl where

import Shared.Model.Context.AclContext

checkViewPermission _ = checkPermission _KNOWLEDGE_MODEL_EDITORS_USE_ROLE_PERMISSION

checkEditPermission _ = checkPermission _KNOWLEDGE_MODEL_EDITORS_USE_ROLE_PERMISSION
