module Shared.Model.User.RolePermission where

import qualified Data.List as L

_DEV_USE_ROLE_PERMISSION :: String
_DEV_USE_ROLE_PERMISSION = "dev.use"

_TENANTS_MANAGE_ROLE_PERMISSION :: String
_TENANTS_MANAGE_ROLE_PERMISSION = "tenants.manage"

_SETTINGS_MANAGE_ROLE_PERMISSION :: String
_SETTINGS_MANAGE_ROLE_PERMISSION = "settings.manage"

_ORGANIZATION_SETTINGS_MANAGE_ROLE_PERMISSION :: String
_ORGANIZATION_SETTINGS_MANAGE_ROLE_PERMISSION = "organizationSettings.manage"

_ROLES_MANAGE_ROLE_PERMISSION :: String
_ROLES_MANAGE_ROLE_PERMISSION = "roles.manage"

_USERS_MANAGE_ROLE_PERMISSION :: String
_USERS_MANAGE_ROLE_PERMISSION = "users.manage"

_MEMBERS_MANAGE_ROLE_PERMISSION :: String
_MEMBERS_MANAGE_ROLE_PERMISSION = "members.manage"

_USER_GROUPS_MANAGE_ROLE_PERMISSION :: String
_USER_GROUPS_MANAGE_ROLE_PERMISSION = "userGroups.manage"

_WORKSPACES_MANAGE_ROLE_PERMISSION :: String
_WORKSPACES_MANAGE_ROLE_PERMISSION = "workspaces.manage"

_ORGANIZATION_LIBRARY_MANAGE_ROLE_PERMISSION :: String
_ORGANIZATION_LIBRARY_MANAGE_ROLE_PERMISSION = "organizationLibrary.manage"

_DOCUMENT_TEMPLATE_EDITORS_USE_ROLE_PERMISSION :: String
_DOCUMENT_TEMPLATE_EDITORS_USE_ROLE_PERMISSION = "documentTemplates.useEditor"

_DOCUMENT_TEMPLATES_MANAGE_ROLE_PERMISSION :: String
_DOCUMENT_TEMPLATES_MANAGE_ROLE_PERMISSION = "documentTemplates.manage"

_KNOWLEDGE_MODEL_EDITORS_USE_ROLE_PERMISSION :: String
_KNOWLEDGE_MODEL_EDITORS_USE_ROLE_PERMISSION = "knowledgeModels.useEditor"

_KNOWLEDGE_MODELS_MANAGE_ROLE_PERMISSION :: String
_KNOWLEDGE_MODELS_MANAGE_ROLE_PERMISSION = "knowledgeModels.manage"

_PROJECT_TEMPLATES_MANAGE_ROLE_PERMISSION :: String
_PROJECT_TEMPLATES_MANAGE_ROLE_PERMISSION = "projects.manageTemplates"

_PROJECTS_CREATE_ROLE_PERMISSION :: String
_PROJECTS_CREATE_ROLE_PERMISSION = "projects.create"

_PROJECTS_COMMENT_ROLE_PERMISSION :: String
_PROJECTS_COMMENT_ROLE_PERMISSION = "projects.comment"

_PROJECTS_EDIT_ROLE_PERMISSION :: String
_PROJECTS_EDIT_ROLE_PERMISSION = "projects.edit"

_PROJECTS_MANAGE_ROLE_PERMISSION :: String
_PROJECTS_MANAGE_ROLE_PERMISSION = "projects.manage"

_PROJECTS_VIEW_ROLE_PERMISSION :: String
_PROJECTS_VIEW_ROLE_PERMISSION = "projects.view"

workspaceRolePermissions :: [String]
workspaceRolePermissions =
  [ _PROJECTS_VIEW_ROLE_PERMISSION
  , _PROJECTS_COMMENT_ROLE_PERMISSION
  , _PROJECTS_EDIT_ROLE_PERMISSION
  , _PROJECTS_MANAGE_ROLE_PERMISSION
  , _PROJECTS_CREATE_ROLE_PERMISSION
  , _PROJECT_TEMPLATES_MANAGE_ROLE_PERMISSION
  , _KNOWLEDGE_MODEL_EDITORS_USE_ROLE_PERMISSION
  , _KNOWLEDGE_MODELS_MANAGE_ROLE_PERMISSION
  , _DOCUMENT_TEMPLATE_EDITORS_USE_ROLE_PERMISSION
  , _DOCUMENT_TEMPLATES_MANAGE_ROLE_PERMISSION
  , _MEMBERS_MANAGE_ROLE_PERMISSION
  , _ROLES_MANAGE_ROLE_PERMISSION
  , _USER_GROUPS_MANAGE_ROLE_PERMISSION
  , _SETTINGS_MANAGE_ROLE_PERMISSION
  ]

workspaceReachRolePermissions :: [String]
workspaceReachRolePermissions = workspaceRolePermissions L.\\ [_PROJECTS_CREATE_ROLE_PERMISSION]

organizationOnlyRolePermissions :: [String]
organizationOnlyRolePermissions =
  [ _USERS_MANAGE_ROLE_PERMISSION
  , _WORKSPACES_MANAGE_ROLE_PERMISSION
  , _ORGANIZATION_LIBRARY_MANAGE_ROLE_PERMISSION
  , _ORGANIZATION_SETTINGS_MANAGE_ROLE_PERMISSION
  ]

allRolePermissions :: [String]
allRolePermissions = workspaceRolePermissions ++ organizationOnlyRolePermissions

assignableRolePermissions :: [String]
assignableRolePermissions = allRolePermissions L.\\ [_WORKSPACES_MANAGE_ROLE_PERMISSION, _ORGANIZATION_LIBRARY_MANAGE_ROLE_PERMISSION]
